[build]
  command = "npm run build:prod"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

# Production environment variables
[context.production.environment]
  NODE_ENV = "production"
  VITE_APP_NAME = "Fantasy Football Analyzer"
  VITE_APP_VERSION = "1.0.0"
  # Add your FantasyData API key via Netlify dashboard for security

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self' https://site.api.espn.com https://fantasysports.yahooapis.com https://api.sleeper.app https://generativelanguage.googleapis.com"

# SPA Routing - Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API Proxy for CORS handling - Free APIs with debugging headers
[[redirects]]
  from = "/api/espn/*"
  to = "https://site.api.espn.com/apis/site/v2/sports/football/nfl/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify", X-ESPN-Proxy = "Active", Access-Control-Allow-Origin = "*"}

# REMOVED - ESPN Fantasy endpoints are deprecated and return 404
# [[redirects]]
#   from = "/api/espn-fantasy/*"
#   to = "https://site.api.espn.com/apis/v2/sports/football/nfl/fantasy/:splat"
#   status = 200
#   force = true
#   headers = {X-From = "Netlify", X-ESPN-Fantasy-Proxy = "Active", Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/sleeper/*"
  to = "https://api.sleeper.app/v1/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Performance optimizations
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"